name: Learning GitHub Actions
run-name: I am Learning GitHub Actions!
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run script
        run: node index.js